### ISSUE TITLE
Coarse grain polymer chain molecular dynamic simulation using lammps?

### ISSUE THREAD

**Issue by Raj123dev** [simongravelle/lammps-input-files#3]
How to write an input script and data file for single chain polycarbonate in lammps for coarse grained polymer MD simulation?

**Comment by simongravelle** [comment]
You can just imitate some of the python scripts in this repository, and build the data file manually, its just a text file with one line per atom.

**Comment by Raj123dev** [comment]
Is it mandatory to write a python script for MD simulation, Can we not just write an input script and do the simulation in lammps executable?

**Comment by simongravelle** [comment]
No of course you build the files as you want, you can write everything manually if the system is small enough

**Comment by Raj123dev** [comment]
Dear Sir, i want to simulate for single chain of polycarbonate using lammps, please suggest how to generate the data file using lammps only, i am able to generate using matlb but it is not running in my lammps executable showing some error, how to write the input script for polycarbonate, using coarse grain  model.

**Comment by simongravelle** [comment]
I don't know how to do that with LAMMPS only, that does not seems like a good idea anyway.

**Comment by Raj123dev** [comment]
so we have to combine using python or anyother tool? Sir, Do you have any idea about how to start the MD simulation for polycarbonate (coarse grain model) for single polymer chain?

**Comment by simongravelle** [comment]
yes, this is what people are usually doing, using moltemplate or other equivalent tools

**Comment by Raj123dev** [comment]
Sir, Do you have any idea about how to start the MD simulation for polycarbonate (coarse grain model) for single polymer chain?

**Comment by simongravelle** [comment]
Yes for sure, you can take inspiration from the files here for that, but what you are asking is not really something that can be answered quickly in one or two messages.

**Comment by Raj123dev** [comment]
[1-s2.0-S0032386119303490-main.pdf](https://github.com/simongravelle/lammps-input-files/files/14037277/1-s2.0-S0032386119303490-main.pdf)
 this is the paper, which i want to validate, initially i started to simluate for single polymer chain, i am able to simulate PE polymer but for polycarbonate we need coarsed grian model which i am confused on how to actually do for the PC polymer.
